from edc_visit_schedule import FormsCollection, Crf

crf = {}

crfs_prn = FormsCollection(
    Crf(show_order=1, model='esr21_subject.concomitantmedication',
        required=False, additional=False),
    Crf(show_order=2, model='esr21_subject.hospitalisation',
        required=False, additional=False),
    Crf(show_order=3, model='esr21_subject.adverseevent',
        required=False, additional=False),
    Crf(show_order=4, model='esr21_subject.demographicsdata',
        required=False, additional=False),
    Crf(show_order=5, model='esr21_subject.medicalhistory',
        required=False, additional=False),
    Crf(show_order=6, model='esr21_subject.physicalexam',
        required=False, additional=False),
    Crf(show_order=7, model='esr21_subject.rapidhivtesting',
        required=False, additional=False),
    Crf(show_order=8, model='esr21_subject.pregnancystatus',
        required=False, additional=False),
    Crf(show_order=9, model='esr21_subject.seriousadverseevent',
        required=False, additional=False),
    Crf(show_order=10, model='esr21_subject.specialinterestadverseevent',
        required=False, additional=False),
    Crf(show_order=11, model='esr21_subject.pregnancytest',
        required=False, additional=False),
    Crf(show_order=12, model='esr21_subject.vitalsigns',
        required=False, additional=False),
    Crf(show_order=13, model='esr21_subject.covid19results'),
    Crf(show_order=14, model='esr21_subject.vaccinationdetails',
        required=False, additional=False),
    Crf(show_order=15, model='esr21_subject.covid19preventativebehaviours',
        required=False, additional=False),
    Crf(show_order=16, model='esr21_subject.covid19symptomaticinfections',
        required=False, additional=False),
    name='crf_prn')

crfs_initial = FormsCollection(
    Crf(show_order=1, model='esr21_subject.demographicsdata'),
    Crf(show_order=2, model='esr21_subject.medicalhistory'),
    Crf(show_order=3, model='esr21_subject.physicalexam',
        required=False, additional=False),
    Crf(show_order=4, model='esr21_subject.rapidhivtesting'),
    Crf(show_order=5, model='esr21_subject.pregnancystatus',
        required=False, additional=False),
    Crf(show_order=6, model='esr21_subject.pregoutcome', required=False,
        additional=False),
    Crf(show_order=7, model='esr21_subject.vaccinationdetails',
        required=False, additional=False),
    Crf(show_order=8, model='esr21_subject.adverseevent',
        required=False),
    Crf(show_order=9, model='esr21_subject.seriousadverseevent',
        required=False, additional=False),
    Crf(show_order=10, model='esr21_subject.specialinterestadverseevent',
        required=False),
    Crf(show_order=11, model='esr21_subject.vitalsigns'),
    Crf(show_order=12, model='esr21_subject.covid19preventativebehaviours'),
    Crf(show_order=13, model='esr21_subject.pregnancytest',
        required=False, additional=False),
    name='enrollment',
)

crfs_followup = FormsCollection(
    Crf(show_order=1, model='esr21_subject.adverseevent'),
    Crf(show_order=2, model='esr21_subject.seriousadverseevent',
        required=False, additional=False),
    Crf(show_order=3, model='esr21_subject.specialinterestadverseevent',
        required=False),
    Crf(show_order=4, model='esr21_subject.hospitalisation',
        required=False, additional=False),
    Crf(show_order=5, model='esr21_subject.covid19symptomaticinfections'),
    Crf(show_order=6, model='esr21_subject.pregnancystatus',
        required=False),
    Crf(show_order=7, model='esr21_subject.pregoutcome', required=False,
        additional=False),
    name='followup',
)

crfs_day_70_170 = FormsCollection(
    Crf(show_order=1, model='esr21_subject.physicalexam'),
    Crf(show_order=2, model='esr21_subject.vitalsigns'),
    Crf(show_order=3, model='esr21_subject.pregoutcome', required=False,
        additional=False),
    Crf(show_order=4, model='esr21_subject.pregnancystatus',
        required=False),
    Crf(show_order=5, model='esr21_subject.vaccinationdetails'),
    Crf(show_order=6, model='esr21_subject.adverseevent',
        required=False),
    Crf(show_order=7, model='esr21_subject.seriousadverseevent',
        required=False),
    Crf(show_order=8, model='esr21_subject.specialinterestadverseevent',
        required=False),
    Crf(show_order=9, model='esr21_subject.pregnancytest', required=False),
    Crf(show_order=10, model='esr21_subject.demographicsdata', required=False),
    Crf(show_order=11, model='esr21_subject.medicalhistory', required=False),
    Crf(show_order=12, model='esr21_subject.rapidhivtesting', required=False),
    Crf(show_order=13, model='esr21_subject.covid19preventativebehaviours',
        required=False),
    name='day_70_170',
)

crfs_ill_initial = FormsCollection(
    Crf(show_order=1, model='esr21_subject.medicalhistory'),
    Crf(show_order=2, model='esr21_subject.targetedphysicalexamination'),
    Crf(show_order=3, model='esr21_subject.concomitantmedication'),
    Crf(show_order=4, model='esr21_subject.vitalsigns'),
    Crf(show_order=5, model='esr21_subject.covid19symptomaticinfections'),
    Crf(show_order=6, model='esr21_subject.seriousadverseevent',
        required=False),
    Crf(show_order=7, model='esr21_subject.pregoutcome', required=False,
        additional=False),
    name='ill_initial',
)

crfs_ill_4 = FormsCollection(
    Crf(show_order=1, model='esr21_subject.concomitantmedication'),
    Crf(show_order=2, model='esr21_subject.covid19symptomaticinfections'),
    Crf(show_order=3, model='esr21_subject.seriousadverseevent',
        required=False),
    Crf(show_order=4, model='esr21_subject.pregoutcome', required=False,
        additional=False),
    name='ill_day4',
)

crfs_ill_28 = FormsCollection(
    Crf(show_order=1, model='esr21_subject.targetedphysicalexamination'),
    Crf(show_order=2, model='esr21_subject.concomitantmedication'),
    Crf(show_order=3, model='esr21_subject.vitalsigns'),
    Crf(show_order=4, model='esr21_subject.covid19symptomaticinfections'),
    Crf(show_order=5, model='esr21_subject.seriousadverseevent',
        required=False),
    Crf(show_order=6, model='esr21_subject.pregoutcome', required=False,
        additional=False),
    name='ill_day28',
)

crf.update({'enrollment': crfs_initial,
            'day_70_170': crfs_day_70_170,
            'followup': crfs_followup,
            'ill_initial': crfs_ill_initial,
            'ill_day4': crfs_ill_4,
            'ill_day28': crfs_ill_28,
            'crf_prn': crfs_prn})
